In [ ]:
/ __truediv__
// __floordiv__
>= __ge__

# Abstraction

In [1]:
from abc import ABC,abstractmethod
class Car(ABC):
    @abstractmethod
    def speed(self):
        print('faster')
class Tesla(Car):
    def speed(self):
        print('150 km/h')
class Maruti(Car):
    def speed(self):
        print('80 km/h')
t=Tesla()
t.speed()

150 km/h


657. 
Write a Python Program to Find the Net Salary of Employee using Inheritance.
Create three Class Employee, Perks, NetSalary. Make an Employee class as an abstract class.
Employee class should have methods for following tasks.- To get employee details like employee id, name and salary from user. - To print the Employee details. - return Salary.- An abstract method emp_id.
Perks class should have methods for following tasks.- To calculate DA, HRA, PF. - To print the individual and total of Perks (DA+HRA-PF).
Netsalary class should have methods for following tasks.- Calculate the total Salary after Perks.- Print employee detail also prints DA, HRA, PF and net salary.
Note 1: DA-35%, HRA-17%, PF-12%
Note 2: It is compulsory to create objects and demonstrating the methods with 
              Correct output.                                                                                                                                       Example:
Employee ID: 1
Employee Name: John
Employee Basic Salary: 25000
DA: 8750.0
HRA: 4250.0
PF: 3000.0
Total Salary: 35000.

In [ ]:
from abc import ABC,abstractmethod
class Employee(ABC):
    def getdetail(self):
        self.emp_id=input("enter id = ")
        self.name=input("enter name = ")
        self.salary=int(input("enter basic salary = "))
    def print_detail(self):
        print('name=',self.name,'id=',self.id,'basic salary=',self.salary)
    def getsalary(self):
        return self.salary
    @abstractmethod
    def


# numpy

In [2]:
import numpy as np
a1=np.array(23)
print(a1)
print(a1.ndim)
print(a1.shape)

23
0
()


In [3]:
a2=np.array([1,2,3,4,5,6])
print(a2)
print(type(a2))
print(a2.ndim)
print(a2.shape)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
1
(6,)


In [4]:
a3=np.array([[1,2,3],[4,5,6]])
print(a3)
print(a3.ndim)
print(a3.shape)
print(a3[0])
print(a3[1][0:2])
print(a3[0:2,1])

[[1 2 3]
 [4 5 6]]
2
(2, 3)
[1 2 3]
[4 5]
[2 5]


In [7]:
a4=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a4)
print(a4.ndim)
print(a4.shape)
print(a4[0])
print(a4[1,0])
print(a4[0,1,1])
print(a4[1,0,-1])
print(a4[0:2,1,0:2])
print(a4[1,0:2,0:2])
print(a4[0:1,0,0:1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)
[[1 2 3]
 [4 5 6]]
[7 8 9]
5
9
[[ 4  5]
 [10 11]]
[[ 7  8]
 [10 11]]
[[1]]


In [16]:
a5=np.array([1,2,3,4,5,6])
print(a5.reshape(3,2))
print(a5.reshape(3,2,1))
print(a5.reshape(-2,3))

[[1 2]
 [3 4]
 [5 6]]
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]
[[1 2 3]
 [4 5 6]]


In [17]:
a=np.array([[1,2,3,9,10],[4,5,6,7,8]])
for i,j in np.ndenumerate(a):
    print(i,'--',j)

(0, 0) -- 1
(0, 1) -- 2
(0, 2) -- 3
(0, 3) -- 9
(0, 4) -- 10
(1, 0) -- 4
(1, 1) -- 5
(1, 2) -- 6
(1, 3) -- 7
(1, 4) -- 8
