In [4]:
import numpy as np
a1=np.array([1,2,3])
a2=np.array([11,12,13])
n=np.concatenate((a1,a2))
print(n)

[ 1  2  3 11 12 13]


In [5]:
import numpy as np
a1=np.array([[1,2,3],[4,5,6]])
a2=np.array([[11,12,13],[14,15,16]])
n=np.concatenate((a1,a2),axis=0)
print(n)

[[ 1  2  3]
 [ 4  5  6]
 [11 12 13]
 [14 15 16]]


In [7]:
import numpy as np
a1=np.array([[1,2,3],[4,5,6]])
a2=np.array([[11,12,13],[14,15,16]])
n=np.concatenate((a1,a2),axis=1)
print(n)

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]]


In [8]:
import numpy as np
a1=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
a2=np.array([[[11,12,13],[14,15,16]],[[11,12,13],[14,15,16]]])
n=np.concatenate((a1,a2),axis=0)
print(n)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]]]


In [9]:
import numpy as np
a1=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
a2=np.array([[[11,12,13],[14,15,16]],[[11,12,13],[14,15,16]]])
n=np.concatenate((a1,a2),axis=1)
print(n)

[[[ 1  2  3]
  [ 4  5  6]
  [11 12 13]
  [14 15 16]]

 [[ 1  2  3]
  [ 4  5  6]
  [11 12 13]
  [14 15 16]]]


In [10]:
import numpy as np
a1=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
a2=np.array([[[11,12,13],[14,15,16]],[[11,12,13],[14,15,16]]])
n=np.concatenate((a1,a2),axis=2)
print(n)

[[[ 1  2  3 11 12 13]
  [ 4  5  6 14 15 16]]

 [[ 1  2  3 11 12 13]
  [ 4  5  6 14 15 16]]]


In [12]:
import numpy as np
a1=np.array([1,2,3,4,5,6])
n=np.array_split(a1,2)
n1=np.array_split(a1,7)
print(n)
print(n1)

[array([1, 2, 3]), array([4, 5, 6])]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32)]


In [14]:
import numpy as np
a1=np.array([1,2,3,4,5,6])
print(np.where(a1==4))

(array([3], dtype=int64),)


In [15]:
import numpy as np
a1=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(np.where(a1%2==0))

(array([0, 0, 0, 1, 1, 1], dtype=int64), array([0, 1, 1, 0, 1, 1], dtype=int64), array([1, 0, 2, 1, 0, 2], dtype=int64))


In [17]:
import numpy as np
a1=np.array([1,4,3,4,5,0])
print(np.sort(a1))

[0 1 3 4 4 5]


In [18]:
import numpy as np
a1=np.array([1,True,False,0])
print(np.sort(a1))

[0 0 1 1]


In [19]:
import numpy as np
a1=np.array([[[1,6,3],[4,5,0]],[[1,2,0],[8,5,6]]])
print(np.sort(a1))

[[[1 3 6]
  [0 4 5]]

 [[0 1 2]
  [5 6 8]]]


# Random

In [20]:
from numpy import random
x=random.randint(100)
print(x)

28


In [21]:
x=random.randint(100,size=(5))
print(x)

[32  0 56 50 29]


In [22]:
x=random.randint(100,size=(5,3))
print(x)

[[81 92 55]
 [ 9  2 49]
 [40 69 15]
 [38 99 64]
 [83 94 31]]


In [24]:
y=random.rand()
print(y)

0.5960438761132449


In [25]:
y=random.rand(3,2)
print(y)

[[0.09901483 0.52246025]
 [0.70743218 0.47842157]
 [0.52312941 0.25107879]]


In [35]:
z=random.choice([3,6,9,2,7])
print(z)

7


In [37]:
z=random.choice([3,6,9,2,7],size=(2,3))
print(z)

[[7 7 3]
 [3 9 6]]


In [66]:
# task

import numpy as np
a1=np.array([[22,18,14,15],[23,15,22,18],[24,17,19,20],[16,19,13,21]])
etc=[22,23,24,24]
s5=[11,12,13,14,15]
s6=[10,9,6,5,14]

n=np.array(np.array_split(etc,4)) # n=etc.reshape(-1,1)
marks=np.concatenate((a1,n),axis=1)
print("marks with etc : \n",marks)

s5=np.array(s5).reshape(1,-1)
s6=np.array(s6).reshape(1,-1)
marks=np.concatenate((marks,s5,s6),axis=0)
print("marks after adding s5 and s6: \n",marks)

total= marks.sum(axis=1,keepdims=True)
print(total)

marks=np.concatenate((marks,total),axis=1)
print("marks after total: \n",marks)

print("after sorting:\n",np.array(sorted(marks,key=lambda x:x[-1], reverse=True)))

marks with etc : 
 [[22 18 14 15 22]
 [23 15 22 18 23]
 [24 17 19 20 24]
 [16 19 13 21 24]]
marks after adding s5 and s6: 
 [[22 18 14 15 22]
 [23 15 22 18 23]
 [24 17 19 20 24]
 [16 19 13 21 24]
 [11 12 13 14 15]
 [10  9  6  5 14]]
[[ 91]
 [101]
 [104]
 [ 93]
 [ 65]
 [ 44]]
marks after total: 
 [[ 22  18  14  15  22  91]
 [ 23  15  22  18  23 101]
 [ 24  17  19  20  24 104]
 [ 16  19  13  21  24  93]
 [ 11  12  13  14  15  65]
 [ 10   9   6   5  14  44]]
after sorting:
 [[ 24  17  19  20  24 104]
 [ 23  15  22  18  23 101]
 [ 16  19  13  21  24  93]
 [ 22  18  14  15  22  91]
 [ 11  12  13  14  15  65]
 [ 10   9   6   5  14  44]]
